### ISSUE TITLE
Issue with Linux ARMv8

### ISSUE THREAD

**Issue by amontoison** [ararslan/CirrusCI.jl#22]
I opened a [pull request](https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/695) in Krylov.jl repository for testing the package on platforms not supported by GitHub Actions and I have the following error with Linux ARMv8:
```
cirrusjl build
/tmp/scripts9566c74d10037c4d7bbb0407d1e2c649.sh: line 5: cirrusjl: command not found
Exit status: 127
```

**Comment by giordano** [comment]
Is https://github.com/giordano/Cuba.jl/blob/0516ab9aa1b289ecedc2125187e79dfe13ae1598/.cirrus.yml of any help?

**Comment by amontoison** [comment]
Yes, I added these lines
```shell
    set -x
    if command -v apt; then
        apt update
        apt install -y curl
    fi
```
and It fixed the ARMv8 build but it broke the Apple M1 one:
```
URL="https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh"
set -x
if command -v apt; then
    apt update
    apt install -y curl
fi
+ command -v apt
/usr/bin/apt
+ apt update
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
```

**Comment by ararslan** [comment]
Wow, M1 Macs have a `/usr/bin/apt`, I just confirmed on a local machine. I have no idea what it is. That's very annoying. Maybe try
```sh
if [ "$(uname -s)" = "Linux" ] && command -v apt; then
```

**Comment by ararslan** [comment]
Looks like that fixed things in your Krylov.jl PR so I added it to the recommended templates in the README. Thanks for the report and sorry for the trouble!

**Comment by amontoison** [comment]
Yes, It fixed the issue. Thanks for your help @giordano and @ararslan!
