### ISSUE TITLE
FreeBSD failures

### ISSUE THREAD

**Issue by dpo** [ararslan/CirrusCI.jl#5]
I get a number of seemingly random failures of this sort on FreeBSD: https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/pull/40/checks?check_run_id=456072504

Any idea what causes them?

**Comment by giordano** [comment]
It may be an issue in Julia :thinking:

**Comment by ararslan** [comment]
Yes, that definitely seems like a Julia bug. Can you open an issue?

**Comment by ararslan** [comment]
Closing in favor of the upstream issue.
