### ISSUE TITLE
pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2

### ISSUE THREAD

**Issue by dpo** [ararslan/CirrusCI.jl#7]
I'm getting this kind of failure on CirrusCI in the "install phase" of the build:
```
sh -c "$(fetch https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh -o -)"
-                                                     4905  B 8585 kBps    00s
Updating FreeBSD repository catalogue...
Fetching meta.txz: . done
pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2
repository FreeBSD has no meta file, using default settings
Fetching packagesite.txz: .......... done
pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2
pkg: Repository FreeBSD load error: meta cannot be loaded No error: 0
Unable to open created repository FreeBSD
Unable to update repository FreeBSD
Error updating repositories!
Exit status: 3
```
Example: https://cirrus-ci.com/task/6087836260630528?command=install

Any ideas what's happening?

Thanks!

**Comment by ararslan** [comment]
Ugh, I have no idea. That looks like a problem on Cirrus' end. Could you try with `os: freebsd` on Travis?

**Comment by dpo** [comment]
Didn't know there was such a thing. It appears to work on Travis, so the problem is with Cirrus. Thanks!

https://travis-ci.org/github/JuliaSmoothOptimizers/Krylov.jl/builds/673660553

**Comment by dpo** [comment]
FYI using a different image on Cirrus appears to resolve the issue. There's still some weirdness with Julia nightly though: https://cirrus-ci.com/task/4801567610109952?command=install#L2

**Comment by ararslan** [comment]
> Didn't know there was such a thing

Yes, Travis support for FreeBSD is quite new and hasn't been officially announced yet. Once it's official I'll start recommending people use Travis FreeBSD builds for Julia instead of CirrusCI.jl since Cirrus seems to regularly encounter odd, unrelated issues.

**Comment by ararslan** [comment]
PSA to anyone reading this, as it seems others (albeit 2 years ago) have linked here: Since Travis is now basically unused by the modern Julia ecosystem and Cirrus has become more robust, particularly when using more recent FreeBSD images, I will not recommend people use Travis for FreeBSD and will devote more time to ensuring the best possible experience with Cirrus.
